name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'dependencies'
  - title: '🚦 Tests'
    labels:
      - 'test'
      - 'tests'
exclude-labels:
  - 'skip-changelog'
  - 'no-changelog'
change-template: '* $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## What's Changed
  $CHANGES